'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol ? "symbol" : typeof obj; };

// get timestamp of current time
var getNow = function getNow() {
  return new Date().getTime();
};
// get a random number
var getRandomNumber = function getRandomNumber() {
  return Math.random().toString().substr(2);
};
// remove dom node
var removeElement = function removeElement(elem) {
  var parent = elem.parentNode;

  if (parent && parent.nodeType !== 11) {
    parent.removeChild(elem);
  }
};
// parse the final url of request
var parseUrl = function parseUrl(url, params) {
  var paramsStr = '';

  if (typeof params === 'string') {
    paramsStr = params;
  } else if ((typeof params === 'undefined' ? 'undefined' : _typeof(params)) === 'object') {
    Object.keys(params).forEach(function (key) {
      if (url.indexOf(key + '=') < 0) {
        paramsStr += '&' + key + '=' + encodeURIComponent(params[key]);
      }
    });
  }
  // add a timestampe to remove cache
  paramsStr += '&_time=' + getNow();

  if (paramsStr[0] === '&') {
    paramsStr = paramsStr.substr(1);
  }

  return url + (url.indexOf('?') === -1 ? '?' : '&') + paramsStr;
};
/**
 * jsonp connection
 * @param {String} url     The request url
 * @param {Object} options method, credentials, body, headers, params, type
 */
function getJSONP(url, options) {
  return new Promise(function (resolve, reject) {
    if (!url) {
      reject(new Error('No request url'));
    }

    var _ref = options || {};

    var _ref$params = _ref.params;
    var params = _ref$params === undefined ? {} : _ref$params;
    var _ref$timeout = _ref.timeout;
    var timeout = _ref$timeout === undefined ? 15000 : _ref$timeout;
    // the funtion name of callback function

    var name = void 0;
    var timer = void 0;
    var requestUrl = parseUrl(url, params);
    // check whether the callbacl name has been defined
    var match = /callback=(\w+)/.exec(requestUrl);

    if (match && match[1]) {
      name = match[1];
    } else {
      // generate a random function name if no callback name was defined
      // return a function name generated by timestamp and random number
      // eg: jsonp_1355750852040_8260732076596469
      name = 'jsonp_' + getNow() + '_' + getRandomNumber();
      requestUrl += '&callback=' + name;
    }

    // create a script element
    var script = document.createElement('script');
    script.type = 'text/javascript';
    // set the request url
    script.src = requestUrl;
    // set the id of dom node which can be used to find this node
    script.id = 'id_' + name;

    var cleanUp = function cleanUp() {
      // exec callback and remove the callback
      window[name] = undefined;
      // get the script node
      var elem = document.getElementById('id_' + name);
      // remove added script node
      removeElement(elem);

      if (timer) {
        clearTimeout(timer);
      }
    };

    if (timeout) {
      timer = setTimeout(function () {
        cleanUp();
        reject(new Error('Timeout'));
      }, timeout);
    }

    // the callback when request finish
    window[name] = function (json) {
      cleanUp();
      // exec callback
      resolve(json);
    };

    // add script node in head
    var head = document.getElementsByTagName('head');

    if (head && head[0]) {
      head[0].appendChild(script);
    }
  });
}

exports.default = getJSONP;