// get timestamp of current time
const getNow = () => (new Date()).getTime();
// get a random number
const getRandomNumber = () => Math.random().toString().substr(2);
// remove dom node
const removeElement = (elem) => {
  const parent = elem.parentNode;

  if (parent && parent.nodeType !== 11) {
    parent.removeChild(elem);
  }
};
// parse the final url of request
const parseUrl = (url, params) => {
  let paramsStr = '';

  if (typeof params === 'string') {
    paramsStr = params;
  } else if (typeof params === 'object') {
    Object.keys(params).forEach(key => {
      if (url.indexOf(`${key}=`) < 0) {
        paramsStr += `&${key}=${encodeURIComponent(params[key])}`;
      }
    });
  }
  // add a timestampe to remove cache
  paramsStr += `&_time=${getNow()}`;

  if (paramsStr[0] === '&') {
    paramsStr = paramsStr.substr(1);
  }

  return url + (url.indexOf('?') === -1 ? '?' : '&') + paramsStr;
};
/**
 * jsonp connection
 * @param {String} url     The request url
 * @param {Object} options method, credentials, body, headers, params, type
 */
function getJSONP(url, options) {
  return new Promise((resolve, reject) => {
    if (!url) {
      reject(new Error('No request url'));
    }

    const { params = {}, timeout = 15000 } = options || {};
    // the funtion name of callback function
    let name;
    let timer;
    let requestUrl = parseUrl(url, params);
    // check whether the callbacl name has been defined
    const match = /callback=(\w+)/.exec(requestUrl);

    if (match && match[1]) {
      name = match[1];
    } else {
      // generate a random function name if no callback name was defined
      // return a function name generated by timestamp and random number
      // eg: jsonp_1355750852040_8260732076596469
      name = `jsonp_${getNow()}_${getRandomNumber()}`;
      requestUrl += `&callback=${name}`;
    }

    // create a script element
    const script = document.createElement('script');
    script.type = 'text/javascript';
    // set the request url
    script.src = requestUrl;
    // set the id of dom node which can be used to find this node
    script.id = `id_${name}`;

    const cleanUp = () => {
      // exec callback and remove the callback
      window[name] = undefined;
      // get the script node
      const elem = document.getElementById(`id_${name}`);
      // remove added script node
      removeElement(elem);

      if (timer) {
        clearTimeout(timer);
      }
    };

    if (timeout) {
      timer = setTimeout(() => {
        cleanUp();
        reject(new Error('Timeout'));
      }, timeout);
    }

    // the callback when request finish
    window[name] = (json) => {
      cleanUp();
      // exec callback
      resolve(json);
    };


    // add script node in head
    const head = document.getElementsByTagName('head');

    if (head && head[0]) {
      head[0].appendChild(script);
    }
  });
}

export default getJSONP;
